# -*- coding: utf-8 -*-
"""
工具脚本(非教学本体): 把 ONNX 的量化参数 + 金标准测试向量导出成 C 头文件

产物:
  1) quant_params.h  —— 三层量化参数 + qlayer_t 结构体 + LAYERS[3]
       · W_q   : int8_t[], 行主序 (行 = 输出通道, 列 = 输入通道)
       · S_w   : float[],  per-channel
       · b_int : int32_t[]
       · S_in/z_in/S_out/z_out
  2) golden_test.h   —— 前 N 点的测试向量 (来自 golden_vectors.npz)
       · G_S[N]       输入 (float)
       · G_Y[N]       期望输出 (float, ORT)
       · G_Q1[N][64]  第1层 int8 中间结果 (ORT)  ← 逐位对拍用
       · G_Q2[N][64]  第2层 int8 中间结果 (ORT)

用法(在 Charge_Num 目录, torch 环境):
  python export_c_header.py
"""

import os

import numpy as np
import onnx
from onnx import numpy_helper

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
ONNX_PATH = os.path.join(OUT_DIR, "saw2sin_int8.onnx")
NPZ_PATH = os.path.join(OUT_DIR, "golden_vectors.npz")
N_TEST = 200          # 金标准用前 N 点 (可调)

P = {init.name: numpy_helper.to_array(init)
     for init in onnx.load(ONNX_PATH).graph.initializer}


def fmt_floats(arr, per_line=6, indent="    "):
    """把 float 数组排成紧凑的 C 文本"""
    v = np.asarray(arr).ravel()
    out = []
    for i in range(0, len(v), per_line):
        chunk = ", ".join("%.9g" % float(x) for x in v[i:i + per_line])
        out.append(indent + chunk + ",")
    if out:
        out[-1] = out[-1].rstrip(",")     # 最后一行不留逗号
    return "\n".join(out)


def fmt_ints(arr, per_line=16, indent="    "):
    v = np.asarray(arr).ravel()
    out = []
    for i in range(0, len(v), per_line):
        chunk = ", ".join("%d" % int(x) for x in v[i:i + per_line])
        out.append(indent + chunk + ",")
    if out:
        out[-1] = out[-1].rstrip(",")
    return "\n".join(out)


# 每层的 (W_q, S_w, b_int, S_in, z_in, S_out, z_out)
LAYER_DEFS = [
    # tag,        W 名,                     S_w 名,                  b 名,
    #             S_in 名,                        z_in 名,                        S_out 名,                        z_out 名
    ("L0", "net.0", "s_scale", "s_zero_point",
     "/net/net.1/Relu_output_0_scale", "/net/net.1/Relu_output_0_zero_point"),
    ("L1", "net.2", "/net/net.1/Relu_output_0_scale", "/net/net.1/Relu_output_0_zero_point",
     "/net/net.3/Relu_output_0_scale", "/net/net.3/Relu_output_0_zero_point"),
    ("L2", "net.4", "/net/net.3/Relu_output_0_scale", "/net/net.3/Relu_output_0_zero_point",
     "y_scale", "y_zero_point"),
]

layers = []
for tag, w, s_in_name, z_in_name, s_out_name, z_out_name in LAYER_DEFS:
    W = P["%s.weight_quantized" % w].astype(np.int8)
    S_w = P["%s.weight_scale" % w].astype(np.float32)
    b = P["%s.bias_quantized" % w].astype(np.int32)
    s_in = float(P[s_in_name])
    z_in = int(P[z_in_name])
    s_out = float(P[s_out_name])
    z_out = int(P[z_out_name])
    layers.append(dict(tag=tag, w=w, W=W, S_w=S_w, b=b,
                       s_in=s_in, z_in=z_in, s_out=s_out, z_out=z_out))

# ---------------- quant_params.h ----------------
lines = []
lines.append("/* Auto-generated by export_c_header.py from saw2sin_int8.onnx. DO NOT EDIT. */")
lines.append("#ifndef QUANT_PARAMS_H")
lines.append("#define QUANT_PARAMS_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("/* 一层的全部量化参数. 指针指向下面那些 static const 数组. */")
lines.append("typedef struct {")
lines.append("    const int8_t  *W_q;      /* [out_dim * in_dim], 行主序: 行=输出通道      */")
lines.append("    const float   *S_w;      /* [out_dim], 每输出通道一把尺子              */")
lines.append("    const int32_t *b_int;    /* [out_dim], 已吸收 (b / (S_in*S_w))         */")
lines.append("    double   S_in,  S_out;   /* 输入/输出激活尺子                          */")
lines.append("    int32_t  z_in,  z_out;   /* 输入/输出 zero_point                       */")
lines.append("    int      in_dim, out_dim;")
lines.append("} qlayer_t;")
lines.append("")

for L in layers:
    tag = L["tag"]
    lines.append("/* ---------- %s (%s): %d -> %d ---------- */"
                 % (tag, L["w"], L["W"].shape[1], L["W"].shape[0]))
    lines.append("static const int8_t  %s_W[%d] = {" % (tag, L["W"].size))
    lines.append(fmt_ints(L["W"], per_line=16))
    lines.append("};")
    lines.append("static const float   %s_SW[%d] = {" % (tag, L["S_w"].size))
    lines.append(fmt_floats(L["S_w"]))
    lines.append("};")
    lines.append("static const int32_t %s_B[%d] = {" % (tag, L["b"].size))
    lines.append(fmt_ints(L["b"], per_line=8))
    lines.append("};")
    lines.append("")

lines.append("/* ---------- 三层参数表 (推理时按顺序调用) ---------- */")
lines.append("static const qlayer_t LAYERS[3] = {")
for L in layers:
    # S_in/S_out 存为 double -> 必须 %.17g 才能精确往返 (%.9g 只够 float32)
    lines.append("    { %s_W, %s_SW, %s_B, "
                 "%.17g, %.17g, %d, %d, %d, %d },"
                 % (L["tag"], L["tag"], L["tag"],
                    L["s_in"], L["s_out"], L["z_in"], L["z_out"],
                    L["W"].shape[1], L["W"].shape[0]))
lines.append("};")
lines.append("")
lines.append("#define N_LAYERS 3")
lines.append("")
lines.append("#endif /* QUANT_PARAMS_H */")
lines.append("")

p1 = os.path.join(OUT_DIR, "quant_params.h")
with open(p1, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

# ---------------- golden_test.h ----------------
g = np.load(NPZ_PATH)
s = g["s"][:N_TEST].astype(np.float32).ravel()
y = g["y_int8"][:N_TEST].astype(np.float32).ravel()
q1 = g["q1_int8"][:N_TEST].astype(np.int8)
q2 = g["q2_int8"][:N_TEST].astype(np.int8)
assert q1.shape == (N_TEST, 64) and q2.shape == (N_TEST, 64)

lines = []
lines.append("/* Auto-generated by export_c_header.py from golden_vectors.npz (ORT = oracle). */")
lines.append("#ifndef GOLDEN_TEST_H")
lines.append("#define GOLDEN_TEST_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("#define N_TEST %d" % N_TEST)
lines.append("")
lines.append("/* 输入 s (1000 点均匀覆盖 [-1,1] 的前 %d 点) */" % N_TEST)
lines.append("static const float G_S[N_TEST] = {")
lines.append(fmt_floats(s))
lines.append("};")
lines.append("")
lines.append("/* 期望输出 y (onnxruntime 的真值) */")
lines.append("static const float G_Y[N_TEST] = {")
lines.append(fmt_floats(y))
lines.append("};")
lines.append("")
lines.append("/* 第 1 层 int8 中间结果 (对拍用; 行主序 [N][64]) */")
lines.append("static const int8_t G_Q1[N_TEST][64] = {")
for i in range(N_TEST):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q1[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("/* 第 2 层 int8 中间结果 */")
lines.append("static const int8_t G_Q2[N_TEST][64] = {")
for i in range(N_TEST):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q2[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("#endif /* GOLDEN_TEST_H */")
lines.append("")

p2 = os.path.join(OUT_DIR, "golden_test.h")
with open(p2, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("saved:", p1, "%.1f KB" % (os.path.getsize(p1) / 1024))
print("saved:", p2, "%.1f KB" % (os.path.getsize(p2) / 1024))
print()
print("layer summary (in -> out, W_q elems, S_w elems):")
for L in layers:
    print("  %s %-8s %2d -> %2d   W=%4d  S_w=%3d  S_in=%.9g z_in=%4d  S_out=%.9g z_out=%4d"
          % (L["tag"], L["w"], L["W"].shape[1], L["W"].shape[0], L["W"].size,
             L["S_w"].size, L["s_in"], L["z_in"], L["s_out"], L["z_out"]))
