# -*- coding: utf-8 -*-
"""
工具脚本(非教学本体): 把 ONNX 的量化参数 + 金标准测试向量导出成 C 头文件

产物:
  1) quant_params.h  —— 三层量化参数 + qlayer_t 结构体 + LAYERS[3]
       · W_q   : int8_t[], 行主序 (行 = 输出通道, 列 = 输入通道)
       · S_w   : float[],  per-channel
       · b_int : int32_t[]
       · S_in/z_in/S_out/z_out
  2) golden_test.h   —— 前 N 点的测试向量 (来自 golden_vectors.npz)
       · G_S[N]       输入 (float)
       · G_Y[N]       期望输出 (float, ORT)
       · G_Q1[N][64]  第1层 int8 中间结果 (ORT)  ← 逐位对拍用
       · G_Q2[N][64]  第2层 int8 中间结果 (ORT)

用法(在 Charge_Num 目录, torch 环境):
  python export_c_header.py
"""

import os

import numpy as np
import onnx
from onnx import numpy_helper

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
ONNX_PATH = os.path.join(OUT_DIR, "saw2sin_int8.onnx")
NPZ_PATH = os.path.join(OUT_DIR, "golden_vectors.npz")
N_TEST = 200          # 金标准用前 N 点 (可调)

P = {init.name: numpy_helper.to_array(init)
     for init in onnx.load(ONNX_PATH).graph.initializer}


def fmt_floats(arr, per_line=6, indent="    "):
    """把 float 数组排成紧凑的 C 文本"""
    v = np.asarray(arr).ravel()
    out = []
    for i in range(0, len(v), per_line):
        chunk = ", ".join("%.9g" % float(x) for x in v[i:i + per_line])
        out.append(indent + chunk + ",")
    if out:
        out[-1] = out[-1].rstrip(",")     # 最后一行不留逗号
    return "\n".join(out)


def fmt_ints(arr, per_line=16, indent="    "):
    v = np.asarray(arr).ravel()
    out = []
    for i in range(0, len(v), per_line):
        chunk = ", ".join("%d" % int(x) for x in v[i:i + per_line])
        out.append(indent + chunk + ",")
    if out:
        out[-1] = out[-1].rstrip(",")
    return "\n".join(out)


# 每层的 (W_q, S_w, b_int, S_in, z_in, S_out, z_out)
LAYER_DEFS = [
    # tag,        W 名,                     S_w 名,                  b 名,
    #             S_in 名,                        z_in 名,                        S_out 名,                        z_out 名
    ("L0", "net.0", "s_scale", "s_zero_point",
     "/net/net.1/Relu_output_0_scale", "/net/net.1/Relu_output_0_zero_point"),
    ("L1", "net.2", "/net/net.1/Relu_output_0_scale", "/net/net.1/Relu_output_0_zero_point",
     "/net/net.3/Relu_output_0_scale", "/net/net.3/Relu_output_0_zero_point"),
    ("L2", "net.4", "/net/net.3/Relu_output_0_scale", "/net/net.3/Relu_output_0_zero_point",
     "y_scale", "y_zero_point"),
]

layers = []
for tag, w, s_in_name, z_in_name, s_out_name, z_out_name in LAYER_DEFS:
    W = P["%s.weight_quantized" % w].astype(np.int8)
    S_w = P["%s.weight_scale" % w].astype(np.float32)
    b = P["%s.bias_quantized" % w].astype(np.int32)
    s_in = float(P[s_in_name])
    z_in = int(P[z_in_name])
    s_out = float(P[s_out_name])
    z_out = int(P[z_out_name])
    # B2: 把 z_in 折叠进 bias.  acc = sum W*(x - z_in) + b
    #                                = sum W*x + (b - z_in*rowsum(W)) = sum W*x + b'
    rowsum = W.astype(np.int64).sum(axis=1)                   # (out,) = sum_i W_q[o][i]
    b_fold = b.astype(np.int64) - z_in * rowsum               # int64 中介, 防溢出
    assert b_fold.min() >= -2**31 and b_fold.max() < 2**31, "b' overflows int32!"
    layers.append(dict(tag=tag, w=w, W=W, S_w=S_w, b=b, bf=b_fold.astype(np.int32),
                       s_in=s_in, z_in=z_in, s_out=s_out, z_out=z_out))

# ---------------- quant_params.h ----------------
lines = []
lines.append("/* Auto-generated by export_c_header.py from saw2sin_int8.onnx. DO NOT EDIT. */")
lines.append("#ifndef QUANT_PARAMS_H")
lines.append("#define QUANT_PARAMS_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("/* 一层的全部量化参数. 指针指向下面那些 static const 数组. */")
lines.append("typedef struct {")
lines.append("    const int8_t  *W_q;      /* [out_dim * in_dim], 行主序: 行=输出通道      */")
lines.append("    const float   *S_w;      /* [out_dim], 每输出通道一把尺子              */")
lines.append("    const int32_t *b_int;    /* [out_dim], 已吸收 (b / (S_in*S_w))         */")
lines.append("    const int32_t *b_fold;   /* [out_dim], b_int - z_in*rowsum(W_q): 内层循环不再需要减 z_in */")
lines.append("    double   S_in,  S_out;   /* 输入/输出激活尺子                          */")
lines.append("    int32_t  z_in,  z_out;   /* 输入/输出 zero_point                       */")
lines.append("    int      in_dim, out_dim;")
lines.append("} qlayer_t;")
lines.append("")

for L in layers:
    tag = L["tag"]
    lines.append("/* ---------- %s (%s): %d -> %d ---------- */"
                 % (tag, L["w"], L["W"].shape[1], L["W"].shape[0]))
    lines.append("static const int8_t  %s_W[%d] = {" % (tag, L["W"].size))
    lines.append(fmt_ints(L["W"], per_line=16))
    lines.append("};")
    lines.append("static const float   %s_SW[%d] = {" % (tag, L["S_w"].size))
    lines.append(fmt_floats(L["S_w"]))
    lines.append("};")
    lines.append("static const int32_t %s_B[%d] = {" % (tag, L["b"].size))
    lines.append(fmt_ints(L["b"], per_line=8))
    lines.append("};")
    lines.append("static const int32_t %s_BF[%d] = {   /* folded: b_int - z_in*rowsum(W_q) */"
                 % (tag, L["bf"].size))
    lines.append(fmt_ints(L["bf"], per_line=8))
    lines.append("};")
    lines.append("")

lines.append("/* ---------- 三层参数表 (推理时按顺序调用) ---------- */")
lines.append("static const qlayer_t LAYERS[3] = {")
for L in layers:
    # S_in/S_out 存为 double -> 必须 %.17g 才能精确往返 (%.9g 只够 float32)
    lines.append("    { %s_W, %s_SW, %s_B, %s_BF, "
                 "%.17g, %.17g, %d, %d, %d, %d },"
                 % (L["tag"], L["tag"], L["tag"], L["tag"],
                    L["s_in"], L["s_out"], L["z_in"], L["z_out"],
                    L["W"].shape[1], L["W"].shape[0]))
lines.append("};")
lines.append("")
lines.append("#define N_LAYERS 3")
lines.append("")
lines.append("#endif /* QUANT_PARAMS_H */")
lines.append("")

p1 = os.path.join(OUT_DIR, "quant_params.h")
with open(p1, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

# ---------------- golden_test.h ----------------
g = np.load(NPZ_PATH)
s = g["s"][:N_TEST].astype(np.float32).ravel()
y = g["y_int8"][:N_TEST].astype(np.float32).ravel()
q1 = g["q1_int8"][:N_TEST].astype(np.int8)
q2 = g["q2_int8"][:N_TEST].astype(np.int8)
assert q1.shape == (N_TEST, 64) and q2.shape == (N_TEST, 64)

lines = []
lines.append("/* Auto-generated by export_c_header.py from golden_vectors.npz (ORT = oracle). */")
lines.append("#ifndef GOLDEN_TEST_H")
lines.append("#define GOLDEN_TEST_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("#define N_TEST %d" % N_TEST)
lines.append("")
lines.append("/* 输入 s (1000 点均匀覆盖 [-1,1] 的前 %d 点) */" % N_TEST)
lines.append("static const float G_S[N_TEST] = {")
lines.append(fmt_floats(s))
lines.append("};")
lines.append("")
lines.append("/* 期望输出 y (onnxruntime 的真值) */")
lines.append("static const float G_Y[N_TEST] = {")
lines.append(fmt_floats(y))
lines.append("};")
lines.append("")
lines.append("/* 第 1 层 int8 中间结果 (对拍用; 行主序 [N][64]) */")
lines.append("static const int8_t G_Q1[N_TEST][64] = {")
for i in range(N_TEST):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q1[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("/* 第 2 层 int8 中间结果 */")
lines.append("static const int8_t G_Q2[N_TEST][64] = {")
for i in range(N_TEST):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q2[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("#endif /* GOLDEN_TEST_H */")
lines.append("")

p2 = os.path.join(OUT_DIR, "golden_test.h")
with open(p2, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("saved:", p1, "%.1f KB" % (os.path.getsize(p1) / 1024))
print("saved:", p2, "%.1f KB" % (os.path.getsize(p2) / 1024))

# ==========================================================================
# MCU 版 (F28P55x): float + 编译期预计算 M
# ==========================================================================
N_MCU = 128

lines = []
lines.append("/* Auto-generated by export_c_header.py -- MCU (F28P55x) variant. DO NOT EDIT.")
lines.append(" *")
lines.append(" * Differences vs the PC header (quant_params.h):")
lines.append(" *   1) everything is float32 -- the C2000 FPU is single precision;")
lines.append(" *      'double' is software-emulated and 10~50x slower")
lines.append(" *   2) M is precomputed at build time and lives in FLASH")
lines.append(" *      -- zero runtime init, zero division during inference")
lines.append(" *   3) S_w is not exported (its information is folded into M) -- saves FLASH")
lines.append(" *   4) no b_fold (measured: B2 is not worth it)")
lines.append(" */")
lines.append("#ifndef QUANT_PARAMS_MCU_H")
lines.append("#define QUANT_PARAMS_MCU_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("typedef struct {")
lines.append("    const int8_t  *W_q;      /* [out*in], row-major: row = output channel */")
lines.append("    const int32_t *b_int;    /* [out], pre-absorbed bias                  */")
lines.append("    const float   *M;        /* [out], requantization multiplier          */")
lines.append("    float   S_in,  S_out;")
lines.append("    int32_t z_in,  z_out;")
lines.append("    int     in_dim, out_dim;")
lines.append("} qlayer_mcu_t;")
lines.append("")

mcu_layers = []
for L in layers:
    # M 用 float64 算一次再降到 float32 (单次舍入, 比在 MCU 上现算更准)
    M = (L["s_in"] * L["S_w"].astype(np.float64) / L["s_out"]).astype(np.float32)
    mcu_layers.append(dict(tag=L["tag"], L=L, M=M))

for M_ in mcu_layers:
    L = M_["L"]
    tag = M_["tag"]
    lines.append("/* ---------- %s (%s): %d -> %d ---------- */"
                 % (tag, L["w"], L["W"].shape[1], L["W"].shape[0]))
    lines.append("static const int8_t  %s_W[%d] = {" % (tag, L["W"].size))
    lines.append(fmt_ints(L["W"], per_line=16))
    lines.append("};")
    lines.append("static const int32_t %s_B[%d] = {" % (tag, L["b"].size))
    lines.append(fmt_ints(L["b"], per_line=8))
    lines.append("};")
    lines.append("static const float   %s_M[%d] = {" % (tag, M_["M"].size))
    lines.append(fmt_floats(M_["M"]))
    lines.append("};")
    lines.append("")

lines.append("static const qlayer_mcu_t LAYERS_MCU[3] = {")
for M_ in mcu_layers:
    L = M_["L"]
    tag = M_["tag"]
    lines.append("    { %s_W, %s_B, %s_M, %.9gf, %.9gf, %d, %d, %d, %d },"
                 % (tag, tag, tag, L["s_in"], L["s_out"], L["z_in"], L["z_out"],
                    L["W"].shape[1], L["W"].shape[0]))
lines.append("};")
lines.append("")
lines.append("#define N_LAYERS_MCU 3")
lines.append("")
lines.append("#endif /* QUANT_PARAMS_MCU_H */")
lines.append("")

p3 = os.path.join(OUT_DIR, "quant_params_mcu.h")
with open(p3, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

# ---------------- golden_test_mcu.h (点数缩减到 N_MCU) ----------------
s_m = g["s"][:N_MCU].astype(np.float32).ravel()
y_m = g["y_int8"][:N_MCU].astype(np.float32).ravel()
q1_m = g["q1_int8"][:N_MCU].astype(np.int8)
q2_m = g["q2_int8"][:N_MCU].astype(np.int8)

lines = []
lines.append("/* Auto-generated by export_c_header.py -- MCU golden vectors (ORT = oracle). */")
lines.append("#ifndef GOLDEN_TEST_MCU_H")
lines.append("#define GOLDEN_TEST_MCU_H")
lines.append("")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("#define N_TEST_MCU %d" % N_MCU)
lines.append("")
lines.append("/* input s: first %d points of a uniform 1000-point sweep over [-1,1] */" % N_MCU)
lines.append("static const float G_S_MCU[N_TEST_MCU] = {")
lines.append(fmt_floats(s_m))
lines.append("};")
lines.append("")
lines.append("/* expected output y (onnxruntime oracle) */")
lines.append("static const float G_Y_MCU[N_TEST_MCU] = {")
lines.append(fmt_floats(y_m))
lines.append("};")
lines.append("")
lines.append("static const int8_t G_Q1_MCU[N_TEST_MCU][64] = {")
for i in range(N_MCU):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q1_m[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("static const int8_t G_Q2_MCU[N_TEST_MCU][64] = {")
for i in range(N_MCU):
    lines.append("    { " + ", ".join("%d" % int(v) for v in q2_m[i]) + " },")
lines[-1] = lines[-1].rstrip(",")
lines.append("};")
lines.append("")
lines.append("#endif /* GOLDEN_TEST_MCU_H */")
lines.append("")

p4 = os.path.join(OUT_DIR, "golden_test_mcu.h")
with open(p4, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("saved:", p3, "%.1f KB" % (os.path.getsize(p3) / 1024))
print("saved:", p4, "%.1f KB" % (os.path.getsize(p4) / 1024))
print()
print("MCU variant: M precomputed; S_in/S_out as float; N_TEST_MCU = %d" % N_MCU)
print("MCU data footprint: W_q %d B + b_int %d B + M %d B + golden %d B = %.1f KB"
      % (sum(M_["L"]["W"].size for M_ in mcu_layers),
         sum(M_["L"]["b"].size * 4 for M_ in mcu_layers),
         sum(M_["M"].size * 4 for M_ in mcu_layers),
         N_MCU * (64 * 2 + 4 * 2),
         (sum(M_["L"]["W"].size for M_ in mcu_layers)
          + sum(M_["L"]["b"].size * 4 for M_ in mcu_layers)
          + sum(M_["M"].size * 4 for M_ in mcu_layers)
          + N_MCU * (64 * 2 + 4 * 2)) / 1024.0))
print()
print("layer summary (in -> out, W_q elems, S_w elems):")
for L in layers:
    print("  %s %-8s %2d -> %2d   W=%4d  S_w=%3d  S_in=%.9g z_in=%4d  S_out=%.9g z_out=%4d"
          % (L["tag"], L["w"], L["W"].shape[1], L["W"].shape[0], L["W"].size,
             L["S_w"].size, L["s_in"], L["z_in"], L["s_out"], L["z_out"]))
print()
print("b vs b' (folded) range check -- must fit in int32 (limit 2147483647):")
for L in layers:
    print("  %s  b in [%9d, %9d]   b' in [%9d, %9d]"
          % (L["tag"], int(L["b"].min()), int(L["b"].max()),
             int(L["bf"].min()), int(L["bf"].max())))
